/* Partition-maintenance mirror for one complete archived runtime observation at Microsoft's documented grain. */

CREATE TABLE dbo.query_store_runtime_stats_canonical_PartitionMaintenance
(
	RunID INT NOT NULL,
	plan_id BIGINT NOT NULL,
	runtime_stats_interval_id BIGINT NOT NULL,
	execution_type TINYINT NOT NULL,
	execution_type_desc NVARCHAR(128) NULL,
	contributor_count BIGINT NOT NULL,
	replica_group_id BIGINT NULL,
	replica_count INT NOT NULL,
	first_execution_time DATETIMEOFFSET(7) NOT NULL,
	last_execution_time DATETIMEOFFSET(7) NOT NULL,
	count_executions DECIMAL(38,0) NOT NULL,
	avg_duration FLOAT NULL,
	last_duration BIGINT NULL,
	min_duration BIGINT NULL,
	max_duration BIGINT NULL,
	stdev_duration FLOAT NULL,
	avg_cpu_time FLOAT NULL,
	last_cpu_time BIGINT NULL,
	min_cpu_time BIGINT NULL,
	max_cpu_time BIGINT NULL,
	stdev_cpu_time FLOAT NULL,
	avg_logical_io_reads FLOAT NULL,
	last_logical_io_reads BIGINT NULL,
	min_logical_io_reads BIGINT NULL,
	max_logical_io_reads BIGINT NULL,
	stdev_logical_io_reads FLOAT NULL,
	avg_logical_io_writes FLOAT NULL,
	last_logical_io_writes BIGINT NULL,
	min_logical_io_writes BIGINT NULL,
	max_logical_io_writes BIGINT NULL,
	stdev_logical_io_writes FLOAT NULL,
	avg_physical_io_reads FLOAT NULL,
	last_physical_io_reads BIGINT NULL,
	min_physical_io_reads BIGINT NULL,
	max_physical_io_reads BIGINT NULL,
	stdev_physical_io_reads FLOAT NULL,
	avg_clr_time FLOAT NULL,
	last_clr_time BIGINT NULL,
	min_clr_time BIGINT NULL,
	max_clr_time BIGINT NULL,
	stdev_clr_time FLOAT NULL,
	avg_dop FLOAT NULL,
	last_dop BIGINT NULL,
	min_dop BIGINT NULL,
	max_dop BIGINT NULL,
	stdev_dop FLOAT NULL,
	avg_query_max_used_memory FLOAT NULL,
	last_query_max_used_memory BIGINT NULL,
	min_query_max_used_memory BIGINT NULL,
	max_query_max_used_memory BIGINT NULL,
	stdev_query_max_used_memory FLOAT NULL,
	avg_rowcount FLOAT NULL,
	last_rowcount BIGINT NULL,
	min_rowcount BIGINT NULL,
	max_rowcount BIGINT NULL,
	stdev_rowcount FLOAT NULL,
	avg_num_physical_io_reads FLOAT NULL,
	last_num_physical_io_reads BIGINT NULL,
	min_num_physical_io_reads BIGINT NULL,
	max_num_physical_io_reads BIGINT NULL,
	stdev_num_physical_io_reads FLOAT NULL,
	avg_log_bytes_used FLOAT NULL,
	last_log_bytes_used BIGINT NULL,
	min_log_bytes_used BIGINT NULL,
	max_log_bytes_used BIGINT NULL,
	stdev_log_bytes_used FLOAT NULL,
	avg_tempdb_space_used FLOAT NULL,
	last_tempdb_space_used BIGINT NULL,
	min_tempdb_space_used BIGINT NULL,
	max_tempdb_space_used BIGINT NULL,
	stdev_tempdb_space_used FLOAT NULL,
	avg_page_server_io_reads FLOAT NULL,
	last_page_server_io_reads BIGINT NULL,
	min_page_server_io_reads BIGINT NULL,
	max_page_server_io_reads BIGINT NULL,
	stdev_page_server_io_reads FLOAT NULL,
	last_runtime_stats_contributor_id BIGINT NULL,
	last_value_ambiguous BIT NOT NULL,
	stdev_aggregation_status NVARCHAR(64) NOT NULL,
	observation_state NVARCHAR(20) NOT NULL,

	CONSTRAINT PK_query_store_runtime_stats_canonical_PartitionMaintenance
		PRIMARY KEY NONCLUSTERED
		(RunID, plan_id, execution_type, runtime_stats_interval_id),
	CONSTRAINT CK_query_store_runtime_stats_canonical_PartitionMaintenance_stdev
		CHECK (stdev_aggregation_status IN
			(N'NATIVE_SINGLE_CONTRIBUTOR', N'UNAVAILABLE_MULTIPLE_CONTRIBUTORS')),
	CONSTRAINT CK_query_store_runtime_stats_canonical_PartitionMaintenance_state
		CHECK (observation_state IN (N'COMPLETED', N'PROVISIONAL'))
) ON PS_RunID(RunID);
GO
CREATE CLUSTERED COLUMNSTORE INDEX CCI_query_store_runtime_stats_canonical_PartitionMaintenance
	ON dbo.query_store_runtime_stats_canonical_PartitionMaintenance
	WITH (COMPRESSION_DELAY = 0 MINUTES)
	ON PS_RunID(RunID);
GO
